- name: Install JRE
  apt:
    package: openjdk-8-jre-headless
    state: present

- name: Install RNG
  apt:
    package: rng-tools
    state: present

- name: Install systemd script for the app
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service
  notify: Refresh systemd

- name: Make the app start on boot
  service:
    name: app
    enabled: yes

- name: Upload JAR file
  get_url:
    src: "{{ nexus_server }}/{{ nexus_repository }}/{{ artefact_groupe_id }}/{{ artefact_id }}/{{ artefact_version }}/{{ artefact_id }}-{{ artefact_version }}.{{ artefact_extension }}"
    dest: /home/niclettel/app.jar

- name: Write properties files
  blockinfile:
    name: /home/niclettel/application.yml
    block: "{{ spring_boot_app_properties }}"
    create: yes
  when: spring_boot_app_properties is defined
